#!/bin/bash

# Input bundle file
BUNDLE_FILE="bundle.pem"

# Output directory
OUTPUT_DIR="cert_parts"
mkdir -p "$OUTPUT_DIR"

# Split the bundle
csplit -sz "$BUNDLE_FILE" '/-----BEGIN CERTIFICATE-----/' '{*}' > /dev/null

# Rename the split files
i=0
for file in xx*; do
  mv "$file" "$OUTPUT_DIR/cert_$i.pem"
  ((i++))
done

echo "Certificates extracted to $OUTPUT_DIR/"

